version: '3.2'
services:
  server:
    image: alpine:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app/server/static/:/static/
      - ./bin/linux/server:/server
    ports:
      - 9000:9000
    command: /server -host 0.0.0.0:9000 -db.host db -db.pass dbpasswd -db.user dbuser -db.name ccchat 2>&1

  client1:
    image: alpine:latest
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - ./bin/linux/client:/client
      - ./configs:/conf
    command: /client -host server:9000 -user client1 -gen.number 100 2>&1

  client2:
    image: alpine:latest
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - ./bin/linux/client:/client
      - ./configs:/conf
    command: /client -host server:9000 -user client2 -gen.duration 2m -gen.uppercase true 2>&1
  
  db:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpasswd
      POSTGRES_USER: dbuser
      POSTGRES_DB: ccchat
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      - 5433:5433

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080